version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd server
      - docker build -t timetracker .
  post_build:
    commands:
      - echo Build completed on `date`
      - printf '[{"name":"timetracker","imageUri":"998539017710.dkr.ecr.us-east-1.amazonaws.com/timetracker"}]' > imagedefinitions.json
artifacts:
  files:
      server/**/*
      imagedefinitions.json
    