version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo pre_build phase...
      - REPOSITORY_URI="998539017710.dkr.ecr.us-east-1.amazonaws.com/timetracker"
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - cd server
      - docker build -t timetracker .
  post_build:
    commands:
      - echo Build completed on `date`
      - docker tag timetracker:latest 998539017710.dkr.ecr.us-east-1.amazonaws.com/timetracker:latest
      - docker push 998539017710.dkr.ecr.us-east-1.amazonaws.com/timetracker:latest
      - cd .. 
      - printf '[{"name":"timetracker","imageUri":"998539017710.dkr.ecr.us-east-1.amazonaws.com/timetracker"}]' > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
    